image: node:latest

stages:
  - build
  - test
  - deploy

cache:
      paths:
        - node_modules/

variables:
  CLIENT_PATH: "app/client"

build:
  stage: build
  script:
    - npm install $CLIENT_PATH
  artifacts:
        paths:
          - node_modules/

test:
  stage: test
  script:
    - npm tests $CLIENT_PATH

deploy:
  stage: deploy
  script:
    - docker build . -t localhost:32000/todoapp
    - docker push localhost:32000/todoapp
  only:
    - master
