apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: todoapp-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
  - host: todoapp.com
    http:
      paths:
      - path: /
        backend:
          serviceName: todoapp
          servicePort: 3000
---
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: todoapp-test-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
  - host: test.todoapp.com
    http:
      paths:
      - path: /
        backend:
          serviceName: todoapp-test
          servicePort: 3000
