apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  labels:
    app: nginx
spec:
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: mynginx:local
        imagePullPolicy: Never
        ports:
        - containerPort: 80

apiVersion: v1
kind: Pod
metadata:
  name: todoapp
spec:
  containers:
    - name: todoapp
      image: localhost:32000/todoapp:registry
      imagePullPolicy: Always

apiVersion: mongodb.com/v1
kind: MongoDB
metadata:
  name: MongoDB
spec:
  members: 3
  version: 4.2.2-ent
  opsManager:
    configMapRef:
      name: <configMap.metadata.name>
            # Must match metadata.name in ConfigMap file
  credentials: <mycredentials>
  type: ReplicaSet
  persistent: true
