apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  labels:
    app: nginx
spec:
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: nginx:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 80
        
---

apiVersion: extensions/v1beta1
kind: Pod
metadata:
  name: gitlab
spec:
  containers:
    - name: gitlab
      image: gitlab/gitlab-ce:latest
      imagePullPolicy: Always
      hostAliases:
      - ip: "127.0.0.1"
        hostnames:
        - "gitlab.example.com"
      ports:
      - name: http
        port: 80
        targetPort: 80
      - name: https
        port: 443
        targetPort: 443
      - name: ssh 
        port: 22
        targetPort: 22
      volumeMounts:
      - mountPath: "/etc/gitlab"
        name: etc
      - mountPath: "/var/log/gitlab"
        name: logs
      - mountPath: "/var/opt/gitlab"
        name: opt
      volumes:
    - name: logs
      persistentVolumeClaim:
       claimName: gitlab-volumeclaim
    - name: etc
      persistentVolumeClaim:
       claimName: gitlab-volumeclaim
    - name: opt
      persistentVolumeClaim:
       claimName: gitlab-volumeclaim

---

apiVersion: v1
kind: Pod
metadata:
  name: todoapp
spec:
  containers:
    - name: todoapp
      image: localhost:32000/todoapp
      imagePullPolicy: Always
      ports:
        - containerPort: 3000

---

apiVersion: apps/v1beta1
kind: StatefulSet
metadata:
  name: mongo
spec:
  selector:
    matchLabels:
      role: mongo
      environment: test
  serviceName: "mongo"
  replicas: 3
  template:
    metadata:
      labels:
        role: mongo
        environment: test
    spec:
      terminationGracePeriodSeconds: 10
      containers:
      - name: mongo
        image: mongo
        command:
          - mongod
          - "--replSet"
          - rs0
          - "--smallfiles"
          - "--noprealloc"
        ports:
          - containerPort: 27017
        volumeMounts:
          - name: mongo-persistent-storage
            mountPath: /data/db
      - name: mongo-sidecar
        image: cvallance/mongo-k8s-sidecar
        env:
          - name: MONGO_SIDECAR_POD_LABELS
            value: "role=mongo,environment=test"
  volumeClaimTemplates:
    - metadata:
        name: mongo-persistent-storage
      spec:
        storageClassName: "fast"
        accessModes: ["ReadWriteOnce"]
        resources:
          requests:
            storage: 500Mi

---

apiVersion: v1
kind: volume
metadata:
  name: volumeForAllApplications
spec:
  storageClassName: standard 
  capacity:
    storage: 100Mi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/persistent-volume"

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: gitlab-volumeclaim
spec:
  storageClassName: standard 
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Mi
