apiVersion: v1
kind: ReplicationController
metadata:
  labels:
    name: todoapp-test
    namespace: test
  name: todoapp-controller
spec:
  replicas: 2
  template:
    metadata:
      labels:
        name: todoapp
    spec:
      containers:
      - name: todoapp
        namespace: todoapp
        image: registry.gitlab.com/devops-exercise/lecture-devops-app
        imagePullPolicy: Always
        ports:
          - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  labels:
    name: mongo-test
    namespace: test
  name: mongo-test
spec:
  ports:
    - port: 27017
      targetPort: 27017
  selector:
    name: mongo-test
---
apiVersion: v1
kind: ReplicationController
metadata:
  labels:
    name: mongo
  name: mongo-controller
spec:
  replicas: 1
  template:
    metadata:
      labels:
        name: mongo
    spec:
      containers:
      - image: mongo
        name: mongo-test
        ports:
        - name: mongo-test
          containerPort: 27017
          hostPort: 27017
        volumeMounts:
            - name: mongo-persistent-storage
              mountPath: /data/db
      volumes:
        - name: mongo-persistent-storage
          hostPath:
            path: "/mnt/test/data"
