apiVersion: v1
kind: Namespace
metadata:
    name: production
    labels: 
      name: production
---
apiVersion: v1
kind: ReplicationController
metadata:
  labels:
    name: todoapp
  name: todoapp-controller
  namespace: production
spec:
  replicas: 2
  template:
    metadata:
      labels:
        name: todoapp
    spec:
      containers:
      - name: todoapp
        namespace: todoapp
        image: registry.gitlab.com/devops-exercise/lecture-devops-app:prod
        imagePullPolicy: Always
        ports:
          - containerPort: 3000
        env:
        - name: MONGODB_URL
          value: "mongodb://mongo:27017/todo-app"
---
apiVersion: v1
kind: Service
metadata:
  labels:
    name: todoapp
  name: todoapp
  namespace: production
spec:
  type: NodePort
  ports:
    - nodeport: 31131
      port: 3000
      targetPort: 3000
  selector:
    name: todoapp
---
apiVersion: v1
kind: Service
metadata:
  labels:
    name: mongo
  name: mongo
  namespace: production
spec:
  ports:
    - port: 27017
      targetPort: 27017
  selector:
    name: mongo
---
apiVersion: v1
kind: ReplicationController
metadata:
  labels:
    name: mongo
  name: mongo-controller
  namespace: production
spec:
  replicas: 1
  template:
    metadata:
      labels:
        name: mongo
    spec:
      containers:
      - image: mongo
        name: mongo
        ports:
        - name: mongo
          containerPort: 27017
        volumeMounts:
            - name: mongo-persistent-storage
              mountPath: /data/db
      volumes:
        - name: mongo-persistent-storage
          hostPath:
            path: "/mnt/data"
